### ISSUE TITLE
Changes to logging have reversed string and exception order

### ISSUE THREAD

**Issue by SpiroKyriakidis** [mattgwagner/CertiPay.Common#2]
I tried out Certipay.Common 0.3.1 on I-enroller, but every instance of logging had errors. For example, Log.Fatal(exc, "Failed"); was failing until I changed it to Log.Fatal("Failed", exc);. I'm not sure if you meant to switch the string and exception order and every instance in I-enroller will have to be changed, or if it's just backwards.

**Comment by mattgwagner** [comment]
It was a breaking change. I should have made it more well known but didn't
expect to update it for ienroller. This API is more clear and matches
Log4net and Nlog which are more commonly used.

**Comment by mattgwagner** [comment]
Note the actual API is Log.FatalException for this use case.
